import { Router } from 'express';
import { body, param } from 'express-validator';
import { authenticate } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import * as teams from '../controllers/teams.controller.js';
export const teamsRouter = Router();
teamsRouter.use(authenticate);
const id = param('teamId').toInt().isInt({ min: 1 });
const fields = [body('name').optional().trim().isLength({ min: 1, max: 120 }), body('description').optional().trim().isLength({ max: 2000 })];
teamsRouter.route('/').get(teams.listTeams).post([body('name').trim().isLength({ min: 1, max: 120 }), body('description').optional().trim().isLength({ max: 2000 })], validate, teams.createTeam);
teamsRouter.route('/:teamId').get(id, validate, teams.getTeam).patch([id, ...fields], validate, teams.updateTeam).delete(id, validate, teams.deleteTeam);
teamsRouter.post('/:teamId/members', [id, body('email').isEmail().normalizeEmail(), body('role').optional().isIn(['admin', 'member']), body('rankId').optional({ nullable: true }).isInt({ min: 1 }).toInt()], validate, teams.addMember);
teamsRouter.patch('/:teamId/members/:userId/role', [id, param('userId').toInt().isInt({ min: 1 }), body('role').isIn(['admin', 'member'])], validate, teams.updateMemberRole);
teamsRouter.patch('/:teamId/members/:userId/rank', [id, param('userId').toInt().isInt({ min: 1 }), body('rankId').optional({ nullable: true }).isInt({ min: 1 }).toInt()], validate, teams.updateMemberRank);
teamsRouter.delete('/:teamId/members/me', id, validate, teams.leaveTeam);
teamsRouter.delete('/:teamId/members/:userId', [id, param('userId').toInt().isInt({ min: 1 })], validate, teams.removeMember);
teamsRouter.get('/:teamId/ranks', id, validate, teams.listRanks);
teamsRouter.post('/:teamId/ranks', [id, body('name').trim().isLength({ min: 1, max: 80 }), body('color').optional().matches(/^#[0-9a-fA-F]{6}$/)], validate, teams.createRank);
teamsRouter.patch('/:teamId/ranks/:rankId', [id, param('rankId').toInt().isInt({ min: 1 }), body('name').optional().trim().isLength({ min: 1, max: 80 }), body('color').optional().matches(/^#[0-9a-fA-F]{6}$/)], validate, teams.updateRank);
teamsRouter.delete('/:teamId/ranks/:rankId', [id, param('rankId').toInt().isInt({ min: 1 })], validate, teams.deleteRank);
teamsRouter.get('/:teamId/invitations', id, validate, teams.listInvitations);
teamsRouter.delete('/:teamId/invitations/:invitationId', [id, param('invitationId').toInt().isInt({ min: 1 })], validate, teams.revokeInvitation);
